"""Add thinking field

Revision ID: 1028136b2266
Revises: 9c6d50c24773
Create Date: 2025-09-09 12:01:34.485062

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1028136b2266"
down_revision: Union[str, None] = "9c6d50c24773"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents",
        "summary",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_comment="Summary",
    )
    op.add_column(
        "messages",
        sa.Column("thinking", sa.String(), nullable=True, comment="Thinking"),
    )
    op.create_unique_constraint(None, "messages", ["id"])
    op.create_unique_constraint(None, "sessions", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="unique")
    op.drop_constraint(None, "messages", type_="unique")
    op.drop_column("messages", "thinking")
    op.alter_column(
        "documents",
        "summary",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_comment="Summary",
    )
    # ### end Alembic commands ###
