"""Add document summary

Revision ID: 5a5652d1655b
Revises: 64a69e87d801
Create Date: 2025-09-07 20:02:43.628085

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a5652d1655b"
down_revision: Union[str, None] = "64a69e87d801"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("summary", sa.String(), nullable=True, comment="Summary"),
    )
    op.create_unique_constraint(None, "documents", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="unique")
    op.drop_column("documents", "summary")
    # ### end Alembic commands ###
