"""Add document

Revision ID: 64a69e87d801
Revises:
Create Date: 2025-09-07 11:24:27.194455

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64a69e87d801"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="ID"),
        sa.Column("name", sa.String(), nullable=False, comment="Name"),
        sa.Column(
            "type",
            sa.Enum("PDF", "TXT", name="documenttype"),
            nullable=False,
            comment="Type",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED", "PROCESSED", "COMPLETED", "FAILED", name="documentstatus"
            ),
            nullable=False,
            comment="Status",
        ),
        sa.Column("collection", sa.String(), nullable=False, comment="Collection"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Created at",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Updated at",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documents")
    # ### end Alembic commands ###
