"""Add session and message

Revision ID: 9c6d50c24773
Revises: 5a5652d1655b
Create Date: 2025-09-08 17:41:15.715955

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c6d50c24773"
down_revision: Union[str, None] = "5a5652d1655b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="ID"),
        sa.Column("document_id", sa.Integer(), nullable=False, comment="Document ID"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Created at",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="ID"),
        sa.Column("session_id", sa.Integer(), nullable=False, comment="Session ID"),
        sa.Column(
            "role",
            sa.Enum("USER", "AGENT", name="role"),
            nullable=False,
            comment="Role",
        ),
        sa.Column("content", sa.String(), nullable=False, comment="Content"),
        sa.Column("timestamp", sa.DateTime(), nullable=False, comment="Timestamp"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_session_id"), "messages", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_session_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_table("sessions")
    # ### end Alembic commands ###
