name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --with dev,test

    - name: Check black
      run: poetry run black --check --diff .

    - name: Check isort
      run: poetry run isort --check-only --diff .

    - name: Check ruff
      run: poetry run ruff check .

    - name: Check pyright
      run: poetry run pyright .

    - name: Run tests
      run: poetry run pytest -v --cov=. --cov-report=term-missing --cov-report=xml
